# sample round config
# all endowments can be specified either as a single number or a list of endowments, one for each player in each group
# if an endowment list is shorter than the number of players in the group, endowments wrap back around to the beginning

# number of players in each group or null if there's only one group
players_per_group: 2
# starting cash endowment for each player
initial_points: 500
# starting cash endowment for each player
cash_endowment: 1000
# the amount of the endowment which is a loan
loan_value: 0
# whether or not players are allowed to have negative available cash
allow_short_cash: true
# the amount of cash that players are allowed to borrow when short selling
short_limit_cash: 100
# the length of the round in seconds
period_length: 10
# a multiplier used to change the way currency is displayed to players.
# prices are integers, so all prices are divided by this number before being shown to players.
# a scale of 1000 means that the smallest price a player can enter is 1/1000 or 0.001.
# this should be a power of 10. it'd probably do weird things if it wasn't
currency_scale: 1
# whether or not arbitrage bots are enabled
bots_enabled: false
# the round which is counted for final payoff
pay_round: 2

# this field lists all the possible states and their relative probability of occuring.
# the probability for each state is calculated as that state's prob_weight divided by
# the sum of prob_weight across all states
states:
  X:
    prob_weight: 25
  Y:
    prob_weight: 25
  Z:
    prob_weight: 475
  W:
    prob_weight: 475

# this field describes the asset structure for the round
asset_structure:
  # name of the asset
  X:
    # whether the player be allowed to hold negative quantities of this asset
    allow_short: false
    # the maximum amount of this asset a player is allowed to borrow for short selling
    # only specified when allow_short is true
    short_limit: 10
    # whether or not this is an etf asset
    is_etf: false
    # initial endowment of this asset
    endowment: [8, 2]
    # the state-dependent payoffs for this asset
    # only specified when asset ISN'T an etf
    payoffs:
      X: 318
      Y: 318
      Z: 89
      W: 89
    mypayoffs: [300, 20]
    probabilities: [45, 55]
  Y:
    allow_short: false
    short_limit: 10
    is_etf: false
    endowment: [20, 80]
    payoffs:
      X: 120
      Y: 80
      Z: 120
      W: 80
    mypayoffs: [200, 80 ]
    probabilities: [ 65, 35]
  Z:
    allow_short: true
    short_limit: 10
    is_etf: false
    endowment: [0, 0]
    payoffs:
      X: 100
      Y: 100
      Z: 100
      W: 100
    mypayoffs: [ 100 ]
    probabilities: [ 100 ]
